# Generated by Django 3.2 on 2021-04-15 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=84)),
                ('location', models.CharField(max_length=54)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to='store-photos/')),
                ('description', models.TextField()),
                ('label', models.CharField(choices=[('null', ' '), ('success', 'new'), ('primary', 'bestseller')], max_length=17)),
                ('currently_available', models.BooleanField(default=True)),
                ('next_available_date', models.DateField(blank=True, default=datetime.date.today)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.companystore')),
            ],
            options={
                'unique_together': {('title', 'store')},
            },
        ),
    ]
